[profile.default]
src = "."
out = "out"
libs = ["lib"]

# Enable via_ir for complex contracts (fixes "stack too deep" errors)
via_ir = true
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
